prompts:
  my_chain:
    current: v1
    versions:
      v1:
        system: |
          Ты — опытный переводчик. Просто переведи текст без лишних комментариев.
        user: |
          Переведи текст английский язык:
          \"{input_text}\"
      v2:
        system: |
          Ты переводчик. Переведи текст
        user: |
          Переведи текст на немецкий язык:
          \"{input_text}\"